---
language: java
jdk: openjdk11
dist: focal

git:
  depth: false
  quiet: true

services:
  - docker

cache:
  directories:
    - ${HOME}/.m2/repository

before_cache: rm -rf $HOME/.m2/repository/alfresco-trashcan-cleaner-module

branches:
  only:
    - master
    - /release\/.*/
    - /support\/.*/
    - /feature\/.*/

stages:
  - name: tests
    if: commit_message !~ /\[skip tests\]/
  - name: release
    if: commit_message =~ /\[release\]/ AND branch ~= /^(master|support\/.+|release\/.+)$/ AND type != pull_request AND fork = false

before_install: bash _ci/init.sh

jobs:
  include:
    - name: "Tests"
      stage: tests
      script: mvn -B -U -q clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Ddb.driver=org.postgresql.Driver -Ddb.name=alfresco -Ddb.url=jdbc:postgresql:alfresco -Ddb.username=alfresco -Ddb.password=alfresco
    
    - name: "Release"
      stage: release
      script: travis_wait 60 bash _ci/maven_release.sh
