name: Alfresco Trashcan Cleaner CI

on:
  pull_request:
    branches:
      - master
      - support/**
      - release/**
  push:
    branches:
      - master
      - support/**
      - release/**
  workflow_dispatch:

jobs:
  build_and_release:
      name: "Build and Release"
      uses: Alfresco/alfresco-build-tools/.github/workflows/build-and-release-maven.yml@fix/ACS-4500_fix-skip-tests
      secrets: inherit
      with:
        auto-release: false
        skip-tests: ${{ contains(github.event.head_commit.message, '[skip tests]') }}
        build-args: "-U -Ddb.driver=org.postgresql.Driver -Ddb.name=alfresco -Ddb.url=jdbc:postgresql:alfresco -Ddb.username=alfresco -Ddb.password=alfresco"
        release-args: "-Dmaven.javadoc.skip=true"
        release-branches: "^master$|^support/.+$|^release/.+$"
